### ISSUE TITLE
здравстуйте бебра была не смачной!

### ISSUE THREAD

**Issue by koksraster** [dimitriy2000/random-background#1]
я заказывал у вас проект в виде смачной, нет, в виде смачнейшей бебры, но вы отправили мне бибу!
Прошу пофиксить!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by dimitriy2000** [comment]
На самом деле эта не баг, а фича
